development:
  address: <%= ENV['MAIL_ADDRESS'] %>
  domain_name: ecarriers.com
  email_provider_username: <%= ENV['SENDGRID_USERNAME'] %>
  email_provider_password: <%= ENV['SENDGRID_PASSWORD'] %>
  host: <%= ENV['DEVELOPMENT_HOST'] %>

  google_map_url: https://maps.googleapis.com/maps/api/js?key=AIzaSyBrwtQvQZrCYxjCPEUgdwMTdmTJHqntftY&libraries=places

  password_pepper: nmn9KDN7SqAlH2ZCeRuH13LOfYCo2uXhpBqFyDQXZSfB3gd41zm5JmYFFrgAw5DQdEDiI8XSKTuJzckvpDAqvpaqvqHL6sz1SGUt

  secret_key_base: 501dd04ce207b05d10a8e0dda6e97e9d7581470ef218b7a93d1a2406c6d13d6984fe810ae42b5a4f72ad89fe03283d13ccb4676810fcbc0881b011f493514cf1

test:
  google_map_url: http://maps.googleapis.com/maps/api/js?key=AIzaSyBrwtQvQZrCYxjCPEUgdwMTdmTJHqntftY&libraries=places

  password_pepper: nmn9KDN7SqAlH2ZCeRuH13LOfYCo2uXhpBqFyDQXZSfB3gd41zm5JmYFFrgAw5DQdEDiI8XSKTuJzckvpDAqvpaqvqHL6sz1SGUt

  secret_key_base: 501dd04ce207b05d10a8e0dda6e97e9d7581470ef218b7a93d1a2406c6d13d6984fe810ae42b5a4f72ad89fe03283d13ccb4676810fcbc0881b011f493514cf1

production:
  address: smtp.sendgrid.net
  domain_name: <%= ENV['ECARRIERS_DOMAIN_NAME'] %>
  email_provider_username: <%= ENV['SENDGRID_USERNAME'] %>
  email_provider_password: <%= ENV['SENDGRID_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_HOST'] %>

  google_map_url: https://maps.googleapis.com/maps/api/js?key=AIzaSyBrwtQvQZrCYxjCPEUgdwMTdmTJHqntftY&libraries=places

  password_pepper: <%= ENV['ECARRIERS_PASSWORD_PAPER'] %>

  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>